### PR TITLE
fix setpgrp call on OpenBSD

### PR DESCRIPTION
**Pull request by schultzor**
guessing the other BSDs are similar

### CODE REVIEW

**Comment by jxy** [comment]
Yes for `__FreeBSD__` please.

**Comment by jonathangray** [comment]
setpgid(0, 0) should work without needing the ifdef

**Comment by pouyatafti** [comment]
As @jonathangray points out setpgid(0,0) should work both on Linux and on BSD (tested on NetBSD).

**Comment by halfwit** [comment]
FreeBSD now compiles correctly with this change

**Comment by anths** [comment]
I've created pull request #497 with the simpler setpgrp->setpgid fix (which I've tested on FreeBSD and macOS), as I'm not sure if there's a way to edit pull requests.

**Comment by dancrossnyc** [comment]
Fixed in #497

**Pull request closed without merging**
