### PR TITLE
make 9l accept Linux kernel version 4.x

### LINKED ISSUE #114: Can't build upas/nfs
```
keks@keks-x220 ~/src/plan9port/src/cmd/upas/nfs$ mk install
9c  box.c
9c  decode.c
decode.c:146:8: warning: variable ‘argv’ set but not used [-Wunused-but-set-variable]
  char *argv[4];
        ^~~~
9c  fs.c
fs.c:953:47: warning: variable ‘reset’ set but not used [-Wunused-but-set-variable]
  int i, j, c, type, flag, unflag, flagset, f, reset;
                                               ^~~~~
9c  imap.c
imap.c:348:6: warning: variable ‘prefix’ set but not used [-Wunused-but-set-variable]
  int prefix, len;
      ^~~~~~
9c  main.c
9c  sx.c
9c  thread.c
9c  util.c
9l -o o.mailfs box.o decode.o fs.o imap.o main.o sx.o thread.o util.o 
(.text+0x23): undefined reference to `pthread_detach'
(.text+0xa9): undefined reference to `pthread_mutex_trylock'
(.text+0xdd): undefined reference to `pthread_mutexattr_init'
(.text+0xe7): undefined reference to `pthread_mutexattr_settype'
(.text+0xfa): undefined reference to `pthread_mutexattr_destroy'
(.text+0x23b): undefined reference to `pthread_create'
(.text+0x28c): undefined reference to `pthread_getspecific'
(.text+0x29f): undefined reference to `pthread_setspecific'
(.text+0x2f3): undefined reference to `pthread_key_create'
(.text+0x339): undefined reference to `pthread_key_create'
collect2: error: ld returned 1 exit status
mk: 9l -o o.mailfs ...  : exit status=exit(1)
```

### PR DESCRIPTION
**Pull request by keks**
fixes #114

### CODE REVIEW

**Comment by 0intro** [comment]
Did you run the INSTALL script? The NPTL check should set SYSVERSION=2.6.x in the $PLAN9/config file. 

Consequently, the following condition in `9l` should match and set -lpthread properly.

```
        case "${SYSVERSION:-`uname -r`}" in
        2.6.* | 3.*)
                echo ${SYSVERSION:-`uname -r`}
                extralibs="$extralibs -lpthread"
                ;;
        esac
```

However, since "3.\*" is already supported, I suppose it's fine to support "4.\*" as well.

Could you change the commit description to something like

```
9l: accept Linux kernel version 4.x 

Fixes #114
```

Thanks.

**Comment by keks** [comment]
I first ran the install script but then wanted to build additional stuff. The instructions in mail/README told me to call mk myself, that's why I got the error.

**Comment by 0intro** [comment]
Did you have the PLAN9 environment variable defined before running `mk`?
I'm trying to understand why SYSVERSION wasn't defined in your case.

**Comment by keks** [comment]
Yes, though it might have pointed to a plan9port folder different than I was working in because I first installed through the package manager, then realised I need to build stuff manually, then dowloaded to ~/src. But one of them was definitely set, and the system p9p is version 20170426.9e-2 so it's not terribly out of date.

**Comment by 0intro** [comment]
OK, I see.

I'll merge your change anyway, since 9l is mean to be used even if SYSVERSION hasn't be defined.

**Pull request merged**
