### PR TITLE
devdraw: cocoa metal screen uses a dirty hack to make everything smooth

### LINKED ISSUE #207: devdraw: glitchy flicker in full screen mode on macOS
Devdraw (or acme, I haven't tested other program) has these weird black screen flickers in full screen mode on macOS.

To reproduce:

1. open acme
2. make it full screen and open a few windows
3. click on some _other_ window (if you were in some window, click another one)
4. switch desktops using 4 finger swipe
5. switch desktop back to full screen acme using 4 finger swipe
6. click on _another_ window than the one clicked at step 3

The screen will glitch. It will either become temporarily black during the click, or it will stay black and you need to click again to redraw it.

This is commit ad2d4950 on 10.14.1 running on an iMac.

### PR DESCRIPTION
**Pull request by jxy**
You are going to hate this.

However, this one line fixes #207 #208 #214.

### CODE REVIEW

**Comment by jxy** [comment]
Moving forward, we can probably uses this NSTextView for handling advanced CJK input methods instead of the current manual implementation.  For now, this one pixel sits in the upper left corner with its sole purpose of forcing the composition of the window system to smooth the fullscreen transition.

**Comment by jxy** [comment]
I used 930da16 couple of hours and I really hated that one pixel that changes my cursor.

004368d is a better alternative, which uses an additional transparent layer instead.  This should be completely unnoticeable.

50ad9e0 simplifies the frame buffer drawing a lot.  I had it at the beginning but it was giving bad graphic glitches, but apparently 004368d fixed it proper.

Please test it on your discrete GPUs.

**Comment by 4ad** [comment]
Well, this makes the glitches go away, though I can swear the mouse cursor is a littler more jittery now. Am I imagining things?

**Comment by yarikk** [comment]
It does fix the problem. Didn't notice any problems with the cursor though.

**Comment by yarikk** [comment]
OS Version:            Mac OS X 10.14.2 (18C54)
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)

`Thread 1 Crashed:
0   com.apple.AMDMTLBronzeDriver  	0x00007fff2d21c6f2 amdBronzeMtlTextureStdWriteTileVecDisp2(void*, void*, unsigned int, unsigned int) + 40
1   com.apple.AMDMTLBronzeDriver  	0x00007fff2d218eed BronzeGenerateMicroTileAddresses2D(BronzeCpuTexInterfaceRec const*, ATIMipmapBufferHeader const*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, void (*)(unsigned long long, unsigned int, unsigned int, unsigned int, void*), void*) + 1314
2   com.apple.AMDMTLBronzeDriver  	0x00007fff2d2198f3 amdMtlBronzeTextureStdReplaceTiles(BronzeCpuTexInterfaceRec const*, ATIMipmapBufferHeader const*, ati_si_format_info const*, unsigned long, unsigned int, unsigned long, unsigned long, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) + 267
3   com.apple.AMDMTLBronzeDriver  	0x00007fff2d2193d1 amdMtlBronzeTextureStdAccessRegion(BronzeCpuTexInterfaceRec const*, void (*)(BronzeCpuTexInterfaceRec const*, ATIMipmapBufferHeader const*, ati_si_format_info const*, unsigned long, unsigned int, unsigned long, unsigned long, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int), void (*)(BronzeCpuTexInterfaceRec const*, ATIMipmapBufferHeader const*, ati_si_format_info const*, unsigned long, unsigned int, unsigned long, unsigned long, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int), ATIMipmapBufferHeader const*, ati_si_format_info const*, unsigned long, unsigned int, unsigned long, unsigned long, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) + 579
4   com.apple.AMDMTLBronzeDriver  	0x00007fff2d219785 amdMtlBronzeTextureStdReplaceRegion(BronzeCpuTexInterfaceRec const*, ATIMipmapBufferHeader const*, ati_si_format_info const*, void*, unsigned int, unsigned long, unsigned long, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) + 291
5   com.apple.AMDMTLBronzeDriver  	0x00007fff2d23e8ce -[BronzeMtlTexture replaceRegion:mipmapLevel:withBytes:bytesPerRow:] + 579
6   devdraw                       	0x000000010134d237 _flushmemscreen + 247 (cocoa-screen-metal.m:956)
7   devdraw                       	0x0000000101346a64 _drawmsgwrite + 3300 (devdraw.c:301)
8   devdraw                       	0x000000010134dcbc runmsg + 940 (cocoa-srv.c:211)
9   devdraw                       	0x000000010134d8bb servep9p + 411 (cocoa-srv.c:83)
10  devdraw                       	0x000000010134a5fe +[AppDelegate callservep9p:] + 14 (cocoa-screen-metal.m:116)
11  com.apple.Foundation          	0x00007fff3939a104 __NSThread__start__ + 1218
12  libsystem_pthread.dylib       	0x00007fff64473305 _pthread_body + 126
13  libsystem_pthread.dylib       	0x00007fff6447626f _pthread_start + 70
14  libsystem_pthread.dylib       	0x00007fff64472415 thread_start + 13
 `

**Comment by jxy** [comment]
@yarikk Is the crash related to #221?

**Comment by rsc** [comment]
@jxy what is the state of this PR? Should I merge it?

**Comment by 4ad** [comment]
I've been using this for the past 4.5 months. If there isn't a cleaner way of fixing this, this hack certainly works well enough.

**Comment by jxy** [comment]
@rsc Please merge it.  The conflict is minor.  You should remove the conflicted code section.

**Comment by jxy** [comment]
Rebased on master.

**Comment by jacobvosmaer** [comment]
This seems to also fix color space issues when in full screen (#260).

**Comment by jxy** [comment]
Rebased on master and changed the hack to be setting the colorspace nil.  Many thanks to @jacobvosmaer for discovering the issue with colorspace.

If you have been using the PR, please retest with the latest commit on colorspace.

If all goes well, I will remove the first two commits in this PR, as they are no longer used.

**Comment by jacobvosmaer** [comment]
Thanks, will test at 8a7a27d75be263aa7ae18787ac6f25797b5bbfb2

**Comment by jxy** [comment]
I take that back.  With 8a7a27d some times screen does not redraw after switching to the full screen devdraw.  It would require repeated mouse click to force the redraw.

**Comment by jacobvosmaer** [comment]
Yes I'm seeing glitches too at https://github.com/9fans/plan9port/commit/8a7a27d75be263aa7ae18787ac6f25797b5bbfb2. The screen sometimes reverts back to an earlier state.

**Comment by rsc** [comment]
This seems at least stable enough for others to try too. I'm sure there will be more to work around. One thing I've noticed recently is the cursor not always being redrawn in the new spot immediately after a program-initiated cursor move. When you move the cursor yourself it hops over and redraws in the right spot.

**Comment by mibk** [comment]
> One thing I've noticed recently is the cursor not always being redrawn in the new spot immediately after a program-initiated cursor move. When you move the cursor yourself it hops over and redraws in the right spot.

I've been experiencing this issue ever since I've started using Acme about a year ago. Throughout that time there's been a lot of changes (e.g. the Cocoa Metal rewrite, a lot of fixes, a new version of macOS), but nothing seems to have fixed the problem.

**Comment by jxy** [comment]
> > One thing I've noticed recently is the cursor not always being redrawn in the new spot immediately after a program-initiated cursor move. When you move the cursor yourself it hops over and redraws in the right spot.
> 
> I've been experiencing this issue ever since I've started using Acme about a year ago. Throughout that time there's been a lot of changes (e.g. the Cocoa Metal rewrite, a lot of fixes, a new version of macOS), but nothing seems to have fixed the problem.

That's right.  I guess it started from Sierra or High Sierra.  I tried a couple of ways to move the cursor, but none seemed to help.  It worths opening a separate issue to track this.

**Comment by mccoyst** [comment]
I can't yet tell if it's related to #225, but since this was merged into master, I've noticed that acme will sometimes not update the window after edits, or only update a portion of the window. It doesn't seem like it's reverting, or it's reverting so quickly that I can't see it as it happens. This happens in both windowed and fullscreen modes. For example (using `|` to represent the cursor and `----` for the top and bottom of the in-acme window):

    ----
    line 1|
    line 2
    line 3
    line 4
    
    ----

Typing Enter will sometimes not be reflected in the window until I click on the window (or scroll with the arrow keys, etc.). In other words, it looks the same, even though the buffer did change. It also happens when typing backspace with the cursor at the beginning of the line.

Another thing I've seen is that a narrower-than-correct "rectangle" of the window gets updated after typing. So for the example above, typing Enter could result in a window that looks like this:

    ----
    line 1
    |
    line 2
    line 4
    
    ----

Again, clicking or scrolling redraws everything properly. I've also seen these glitches for horizontally-oriented edits (e.g. adding or deleting a character), and things like `win` where I'll run a command and not see any of the output until I click or scroll.

**Comment by rsc** [comment]
Thanks @mccoyst; filed #268 for your comment.

**Pull request merged**
