### PR TITLE
Get network stats in a portable manner on FreeBSD

### PR DESCRIPTION
**Pull request by bakul**
as the old grody way doesn't work any more on FreeBSD-10 and later.

### CODE REVIEW

**Comment by 0intro** [comment]
Could you change the commit message to something like "auxstats: get network stats in a portable manner on FreeBSD". Thanks.

**Comment by bakul** [comment]
git diff will show that a file in auxstats changed and the commit message describes what the change does. Why force another commit?

**Comment by bakul** [comment]
Thanks.

**Comment by 0intro** [comment]
Merged. Thanks.

**Pull request merged**
